
SELECT * FROM S_PRESTAMOS WHERE ROWNUM <= 10;
SELECT * FROM S_ALUMNOS WHERE ROWNUM <= 10;


CREATE TABLE PRUEBA_USER2 (ID NUMBER);
CREATE SEQUENCE PRUEBA_SEQ_USER2 START WITH 1 INCREMENT BY 1;
DROP TABLE PRUEBA_USER2;
DROP SEQUENCE PRUEBA_SEQ_USER2;

