
DROP PUBLIC SYNONYM S_PRESTAMOS;
DROP PUBLIC SYNONYM S_ALUMNOS;
DROP PUBLIC SYNONYM S_CARRERAS;
DROP PUBLIC SYNONYM S_MULTAS;
DROP SYNONYM S_DETALLE_MULTAS;


CREATE PUBLIC SYNONYM S_PRESTAMOS FOR PRESTAMOS;
CREATE PUBLIC SYNONYM S_ALUMNOS FOR ALUMNOS;
CREATE PUBLIC SYNONYM S_CARRERAS FOR CARRERAS;
CREATE PUBLIC SYNONYM S_MULTAS FOR MULTAS;