
SHOW PDBS;
SHOW CON_NAME;


ALTER SESSION SET CONTAINER = XEPDB1;


SHOW CON_NAME;


DROP ROLE PRY2205_ROL_D;
DROP ROLE PRY2205_ROL_P;

CREATE ROLE PRY2205_ROL_D;
CREATE ROLE PRY2205_ROL_P; 



DROP USER PRY2205_USER1 CASCADE; 
DROP USER PRY2205_USER2 CASCADE;


CREATE USER PRY2205_USER1 IDENTIFIED BY Pass1word$ DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
CREATE USER PRY2205_USER2 IDENTIFIED BY Pass2word$ DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;



GRANT CONNECT TO PRY2205_USER1; 
GRANT CREATE SESSION TO PRY2205_USER1;
GRANT CREATE TABLE TO PRY2205_USER1;    
GRANT CREATE INDEX TO PRY2205_USER1;    
GRANT CREATE VIEW TO PRY2205_USER1;     
GRANT CREATE SYNONYM TO PRY2205_USER1;  
GRANT CREATE PUBLIC SYNONYM TO PRY2205_USER1;
GRANT PRY2205_ROL_D TO PRY2205_USER1;

GRANT CONNECT TO PRY2205_USER2;
GRANT CREATE SESSION TO PRY2205_USER2;
GRANT CREATE SEQUENCE TO PRY2205_USER2;
GRANT CREATE TRIGGER TO PRY2205_USER2;
GRANT CREATE TABLE TO PRY2205_USER2;    
GRANT PRY2205_ROL_P TO PRY2205_USER2;


SELECT GRANTEE, PRIVILEGE, ADMIN_OPTION FROM DBA_SYS_PRIVS WHERE GRANTEE = 'PRY2205_USER1' ORDER BY PRIVILEGE;
SELECT GRANTEE, PRIVILEGE, ADMIN_OPTION FROM DBA_SYS_PRIVS WHERE GRANTEE = 'PRY2205_USER2' ORDER BY PRIVILEGE;



DROP TABLE PRESTAMOS CASCADE CONSTRAINTS;
DROP TABLE MULTAS CASCADE CONSTRAINTS;
DROP TABLE ALUMNOS CASCADE CONSTRAINTS;
DROP TABLE CARRERAS CASCADE CONSTRAINTS;



CREATE TABLE CARRERAS (
    ID_CARRERA NUMBER PRIMARY KEY,
    NOMBRE_CARRERA VARCHAR2(100) NOT NULL
);

CREATE TABLE ALUMNOS (
    ID_ALUMNO NUMBER PRIMARY KEY,
    RUT_ALUMNO VARCHAR2(12) NOT NULL,
    NOMBRE_ALUMNO VARCHAR2(100) NOT NULL,
    ID_CARRERA NUMBER REFERENCES CARRERAS(ID_CARRERA)
);

CREATE TABLE MULTAS (
    ID_MULTA NUMBER PRIMARY KEY,
    ID_CARRERA NUMBER REFERENCES CARRERAS(ID_CARRERA),
    PORCENTAJE_DESCUENTO NUMBER(5,2)
);

CREATE TABLE PRESTAMOS (
    ID_PRESTAMO NUMBER PRIMARY KEY,
    ID_ALUMNO NUMBER REFERENCES ALUMNOS(ID_ALUMNO),
    FECHA_PRESTAMO DATE,
    FECHA_DEVOLUCION DATE, 
    FECHA_ENTREGA_REAL DATE
);



INSERT INTO CARRERAS (ID_CARRERA, NOMBRE_CARRERA) VALUES (100, 'Ingeniería Civil');
INSERT INTO CARRERAS (ID_CARRERA, NOMBRE_CARRERA) VALUES (200, 'Derecho');
INSERT INTO CARRERAS (ID_CARRERA, NOMBRE_CARRERA) VALUES (300, 'Medicina');

INSERT INTO ALUMNOS (ID_ALUMNO, RUT_ALUMNO, NOMBRE_ALUMNO, ID_CARRERA) VALUES (1, '11.111.111-1', 'Juan Pérez', 100);
INSERT INTO ALUMNOS (ID_ALUMNO, RUT_ALUMNO, NOMBRE_ALUMNO, ID_CARRERA) VALUES (2, '22.222.222-2', 'María López', 200);
INSERT INTO ALUMNOS (ID_ALUMNO, RUT_ALUMNO, NOMBRE_ALUMNO, ID_CARRERA) VALUES (3, '33.333.333-3', 'Carlos Ruiz', 300);

INSERT INTO MULTAS (ID_MULTA, ID_CARRERA, PORCENTAJE_DESCUENTO) VALUES (1, 100, 10.00);
INSERT INTO MULTAS (ID_MULTA, ID_CARRERA, PORCENTAJE_DESCUENTO) VALUES (2, 200, 5.00);


INSERT INTO PRESTAMOS (ID_PRESTAMO, ID_ALUMNO, FECHA_PRESTAMO, FECHA_DEVOLUCION, FECHA_ENTREGA_REAL) VALUES (101, 1, DATE '2025-11-01', DATE '2025-11-10', DATE '2025-11-15');
INSERT INTO PRESTAMOS (ID_PRESTAMO, ID_ALUMNO, FECHA_PRESTAMO, FECHA_DEVOLUCION, FECHA_ENTREGA_REAL) VALUES (102, 2, DATE '2025-11-05', DATE '2025-11-15', DATE '2025-11-15');
INSERT INTO PRESTAMOS (ID_PRESTAMO, ID_ALUMNO, FECHA_PRESTAMO, FECHA_DEVOLUCION, FECHA_ENTREGA_REAL) VALUES (103, 3, DATE '2025-11-10', DATE '2025-11-20', NULL);
INSERT INTO PRESTAMOS (ID_PRESTAMO, ID_ALUMNO, FECHA_PRESTAMO, FECHA_DEVOLUCION, FECHA_ENTREGA_REAL) VALUES (104, 3, DATE '2025-12-01', DATE '2025-12-10', DATE '2025-12-12');

COMMIT;



GRANT SELECT ON PRY2205_USER1.PRESTAMOS TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.ALUMNOS TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.CARRERAS TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.MULTAS TO PRY2205_ROL_P;


SELECT * FROM ROLE_TAB_PRIVS WHERE ROLE = 'PRY2205_ROL_P';



BEGIN 
    EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM S_PRESTAMOS'; 
    EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM S_ALUMNOS'; 
    EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM S_CARRERAS'; 
    EXECUTE IMMEDIATE 'DROP PUBLIC SYNONYM S_MULTAS'; 
EXCEPTION WHEN OTHERS THEN NULL; END;
/
DROP SYNONYM S_DETALLE_MULTAS; 


CREATE PUBLIC SYNONYM S_PRESTAMOS FOR PRESTAMOS;
CREATE PUBLIC SYNONYM S_ALUMNOS FOR ALUMNOS;
CREATE PUBLIC SYNONYM S_CARRERAS FOR CARRERAS;
CREATE PUBLIC SYNONYM S_MULTAS FOR MULTAS;


DROP VIEW VW_DETALLE_MULTAS; 

CREATE OR REPLACE VIEW VW_DETALLE_MULTAS AS 
SELECT
    TO_CHAR(P.FECHA_PRESTAMO, 'DD/MM/YYYY') AS "FECHA PRESTAMO",
    TO_CHAR(P.FECHA_DEVOLUCION, 'DD/MM/YYYY') AS "FECHA DEVOLUCION",
    NVL(TO_CHAR(P.FECHA_ENTREGA_REAL, 'DD/MM/YYYY'), 'PENDIENTE') AS "FECHA ENTREGA",
    A.RUT_ALUMNO AS "RUT ALUMNO",
    A.NOMBRE_ALUMNO AS "NOMBRE ALUMNO",
    UPPER(C.NOMBRE_CARRERA) AS "CARRERA",
    CASE 
        WHEN P.FECHA_ENTREGA_REAL > P.FECHA_DEVOLUCION THEN P.FECHA_ENTREGA_REAL - P.FECHA_DEVOLUCION 
        ELSE 0 
    END AS "TOTAL DIAS DE ATRASO",
    TO_CHAR(
        CASE 
            WHEN P.FECHA_ENTREGA_REAL > P.FECHA_DEVOLUCION THEN (P.FECHA_ENTREGA_REAL - P.FECHA_DEVOLUCION) * 500 
            ELSE 0 
        END, 
        'fm$9G999'
    ) AS "TOTAL COBRO POR ATRASO",
    NVL(TO_CHAR(M.PORCENTAJE_DESCUENTO, '90%'), '0%') AS "PORCENTAJE DESCUENTO"
FROM
    PRESTAMOS P 
INNER JOIN ALUMNOS A ON P.ID_ALUMNO = A.ID_ALUMNO
INNER JOIN CARRERAS C ON A.ID_CARRERA = C.ID_CARRERA
LEFT JOIN MULTAS M ON C.ID_CARRERA = M.ID_CARRERA; 

CREATE SYNONYM S_DETALLE_MULTAS FOR VW_DETALLE_MULTAS; 



DROP INDEX IDX_PREST_FECHA_ENTR_REAL;
DROP INDEX IDX_PREST_ID_ALUMNO;

CREATE INDEX IDX_PREST_FECHA_ENTR_REAL ON PRESTAMOS (FECHA_ENTREGA_REAL DESC);
CREATE INDEX IDX_PREST_ID_ALUMNO ON PRESTAMOS (ID_ALUMNO);


SELECT * FROM VW_DETALLE_MULTAS WHERE ROWNUM <= 20 ORDER BY "FECHA ENTREGA" DESC;



SELECT * FROM S_PRESTAMOS WHERE ROWNUM <= 10;
SELECT * FROM S_ALUMNOS WHERE ROWNUM <= 10;


SELECT * FROM PRY2205_USER1.VW_DETALLE_MULTAS 
WHERE ROWNUM <= 10
ORDER BY "FECHA ENTREGA" DESC;


CREATE TABLE PRUEBA_USER2 (ID NUMBER);
CREATE SEQUENCE PRUEBA_SEQ_USER2 START WITH 1 INCREMENT BY 1;
DROP TABLE PRUEBA_USER2;
DROP SEQUENCE PRUEBA_SEQ_USER2;