-- *************************************************************************
-- ** ARCHIVO 2: 02_USER1_CREACION_TABLAS.sql (EJECUTABLE) **
-- ** CONEXIÓN REQUERIDA: pry2205_desarrollado (PRY2205_USER1) **
-- *************************************************************************

-- A. LIMPIEZA TOTAL DE OBJETOS
-- Se borran en orden inverso para evitar conflictos de claves foráneas.
DROP TABLE PRESTAMOS CASCADE CONSTRAINTS;
DROP TABLE MULTAS CASCADE CONSTRAINTS;
DROP TABLE ALUMNOS CASCADE CONSTRAINTS;
DROP TABLE CARRERAS CASCADE CONSTRAINTS;


-- B. CREACIÓN DE TABLAS BASE

CREATE TABLE CARRERAS (
    ID_CARRERA NUMBER PRIMARY KEY,
    NOMBRE_CARRERA VARCHAR2(100) NOT NULL
);

CREATE TABLE ALUMNOS (
    ID_ALUMNO NUMBER PRIMARY KEY,
    RUT_ALUMNO VARCHAR2(12) NOT NULL,
    NOMBRE_ALUMNO VARCHAR2(100) NOT NULL,
    ID_CARRERA NUMBER REFERENCES CARRERAS(ID_CARRERA)
);

CREATE TABLE MULTAS (
    ID_MULTA NUMBER PRIMARY KEY,
    ID_CARRERA NUMBER REFERENCES CARRERAS(ID_CARRERA),
    PORCENTAJE_DESCUENTO NUMBER(5,2) -- Ejemplo: 10.00
);

CREATE TABLE PRESTAMOS (
    ID_PRESTAMO NUMBER PRIMARY KEY,
    ID_ALUMNO NUMBER REFERENCES ALUMNOS(ID_ALUMNO),
    FECHA_PRESTAMO DATE,
    FECHA_DEVOLUCION DATE,
    FECHA_ENTREGA_REAL DATE
);


-- C. POBLACIÓN DE DATOS DE PRUEBA (Fechas: AAAA-MM-DD)

-- CARRERAS
INSERT INTO CARRERAS (ID_CARRERA, NOMBRE_CARRERA) VALUES (100, 'Ingeniería Civil');
INSERT INTO CARRERAS (ID_CARRERA, NOMBRE_CARRERA) VALUES (200, 'Derecho');
INSERT INTO CARRERAS (ID_CARRERA, NOMBRE_CARRERA) VALUES (300, 'Medicina');

-- ALUMNOS
INSERT INTO ALUMNOS (ID_ALUMNO, RUT_ALUMNO, NOMBRE_ALUMNO, ID_CARRERA) VALUES (1, '11.111.111-1', 'Juan Pérez', 100); -- Ingeniería
INSERT INTO ALUMNOS (ID_ALUMNO, RUT_ALUMNO, NOMBRE_ALUMNO, ID_CARRERA) VALUES (2, '22.222.222-2', 'María López', 200); -- Derecho
INSERT INTO ALUMNOS (ID_ALUMNO, RUT_ALUMNO, NOMBRE_ALUMNO, ID_CARRERA) VALUES (3, '33.333.333-3', 'Carlos Ruiz', 300); -- Medicina

-- MULTAS (Descuentos asociados a la carrera)
INSERT INTO MULTAS (ID_MULTA, ID_CARRERA, PORCENTAJE_DESCUENTO) VALUES (1, 100, 10.00); -- 10% descuento para Ingeniería
INSERT INTO MULTAS (ID_MULTA, ID_CARRERA, PORCENTAJE_DESCUENTO) VALUES (2, 200, 5.00);  -- 5% descuento para Derecho
-- (La carrera 300 - Medicina - queda sin entrada en MULTAS para probar el NVL)

-- PRESTAMOS (Pruebas clave para la vista)
-- P1 (ID 101): TARDE (5 días tarde). Aplica multa y 10% de descuento.
INSERT INTO PRESTAMOS (ID_PRESTAMO, ID_ALUMNO, FECHA_PRESTAMO, FECHA_DEVOLUCION, FECHA_ENTREGA_REAL) 
VALUES (101, 1, DATE '2025-11-01', DATE '2025-11-10', DATE '2025-11-15');

-- P2 (ID 102): A TIEMPO. No multa.
INSERT INTO PRESTAMOS (ID_PRESTAMO, ID_ALUMNO, FECHA_PRESTAMO, FECHA_DEVOLUCION, FECHA_ENTREGA_REAL) 
VALUES (102, 2, DATE '2025-11-05', DATE '2025-11-15', DATE '2025-11-15');

-- P3 (ID 103): PENDIENTE. FECHA_ENTREGA_REAL es NULL (el campo "FECHA ENTREGA" debe ser 'PENDIENTE').
INSERT INTO PRESTAMOS (ID_PRESTAMO, ID_ALUMNO, FECHA_PRESTAMO, FECHA_DEVOLUCION, FECHA_ENTREGA_REAL) 
VALUES (103, 3, DATE '2025-11-10', DATE '2025-11-20', NULL);

-- P4 (ID 104): TARDE SIN DESCUENTO (2 días tarde, Carrera 300 no tiene entrada en MULTAS).
INSERT INTO PRESTAMOS (ID_PRESTAMO, ID_ALUMNO, FECHA_PRESTAMO, FECHA_DEVOLUCION, FECHA_ENTREGA_REAL) 
VALUES (104, 3, DATE '2025-12-01', DATE '2025-12-10', DATE '2025-12-12');

COMMIT;