
DROP VIEW VW_DETALLE_MULTAS; 


CREATE OR REPLACE VIEW VW_DETALLE_MULTAS AS 
SELECT
    TO_CHAR(P.FECHA_PRESTAMO, 'DD/MM/YYYY') AS "FECHA PRESTAMO",
    TO_CHAR(P.FECHA_DEVOLUCION, 'DD/MM/YYYY') AS "FECHA DEVOLUCION",
    NVL(TO_CHAR(P.FECHA_ENTREGA_REAL, 'DD/MM/YYYY'), 'PENDIENTE') AS "FECHA ENTREGA",
    A.RUT_ALUMNO AS "RUT ALUMNO",
    A.NOMBRE_ALUMNO AS "NOMBRE ALUMNO",
    UPPER(C.NOMBRE_CARRERA) AS "CARRERA",
    CASE 
        WHEN P.FECHA_ENTREGA_REAL > P.FECHA_DEVOLUCION THEN P.FECHA_ENTREGA_REAL - P.FECHA_DEVOLUCION 
        ELSE 0 
    END AS "TOTAL DIAS DE ATRASO",
    TO_CHAR(
        CASE 
            WHEN P.FECHA_ENTREGA_REAL > P.FECHA_DEVOLUCION THEN (P.FECHA_ENTREGA_REAL - P.FECHA_DEVOLUCION) * 500 
            ELSE 0 
        END, 
        'fm$9G999'
    ) AS "TOTAL COBRO POR ATRASO",
    NVL(TO_CHAR(M.PORCENTAJE_DESCUENTO, '90%'), '0%') AS "PORCENTAJE DESCUENTO"
FROM
    PRESTAMOS P 
INNER JOIN ALUMNOS A ON P.ID_ALUMNO = A.ID_ALUMNO
INNER JOIN CARRERAS C ON A.ID_CARRERA = C.ID_CARRERA
LEFT JOIN MULTAS M ON C.ID_CARRERA = M.ID_CARRERA; 


CREATE SYNONYM S_DETALLE_MULTAS FOR VW_DETALLE_MULTAS; 



DROP INDEX IDX_PREST_FECHA_ENTR_REAL;
DROP INDEX IDX_PREST_ID_ALUMNO;


CREATE INDEX IDX_PREST_FECHA_ENTR_REAL ON PRESTAMOS (FECHA_ENTREGA_REAL DESC);
CREATE INDEX IDX_PREST_ID_ALUMNO ON PRESTAMOS (ID_ALUMNO);


SELECT * FROM VW_DETALLE_MULTAS 
WHERE ROWNUM <= 20
ORDER BY "FECHA ENTREGA" DESC;